<?php var_dump($_GET); 
    
    if(isset($_GET["color"]))
        $color = $_GET["color"];
    
    if(isset($_GET["nom"]))
        $nom = $_GET["nom"];
        
    if(isset($_GET["prenom"]))
        $prenom = $_GET["prenom"];
        
    if(isset($_GET["email"]))
        $email = $_GET["email"];
    
    if(isset($_GET["telephone"]))
        $telephone = $_GET["telephone"];
        
    if(isset($_GET["linkedin"]))
        $linkedin = $_GET["linkedin"];
        
    if(isset($_GET["github"]))
        $github = $_GET["github"];
        
    if(isset($_GET["biographie"]))
        $biographie = $_GET["biographie"];
        
    if(isset($_GET["loisir"]))
        $loisir = $_GET["loisir"];
        
    if(isset($_GET["prog"]))
        $prog = $_GET["prog"];
        
    if(isset($_GET["frame"]))
        $frame = $_GET["frame"];
        
    if(isset($_GET["log"]))
        $log = $_GET["log"];
        
    if(isset($_GET["lang"]))
        $lang = $_GET["lang"];
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            CV
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="style.css" />
    </head>
    <body id="cv" class="<?=$color;?>">
        <header>
            <h1><span><?=$nom; ?></span> <?=$prenom; ?></h1>
            <h2>Intitulé du poste</h2>
        </header>
        <main>
            <section id="left">
                <h3>Informations</h3>
                <section>
                    <h4>
                        Contact
                    </h4>
                    <dl>
                        <dt>
                            Email
                        </dt>
                        <dd>
                            <?=$email; ?>
                        </dd>
                        <dt>
                            Téléphone
                        </dt>
                        <dd>
                            <?php echo $_GET["telephone"];?>
                        </dd>
                        <dt>
                            LinkedIn
                        </dt>
                        <dd>
                            <a href=""><?php echo $_GET["linkedin"];?></a>
                        </dd>
                        <dt>
                            GitHub
                        </dt>
                        <dd>
                            <a href=""><?php echo $_GET["github"];?></a>
                        </dd>
                    </dl>
                </section>
                <section>
                    <h4>Biographie</h4>
                    <p><?php echo $_GET["biographie"];?></p>
                </section>
                <section>
                    <h4>Loisirs</h4>
                    <ul>
                        <?php
                        
                            foreach ($loisir as $item)
                            {
                        ?>
                        <li>
                            <?=$item;?>
                        </li>
                        <?php } ?>
                        
                    </ul>
                </section>
            </section>
            <section id="right">
                <h3>Compétences</h3>
                <section>
                    <h4>Langages des programmation</h4>
                    <ul>
                        <?php 
                        
                            foreach ($prog as $item)
                            {
                        ?>
                            <li><?=$item; ?></li>
                        <?php } ?>
                    </ul>
                </section>
                <section>
                    <h4>Frameworks & Librairies</h4>
                    <ul>
                        <?php 
                        
                            foreach ($frame as $item)
                            {
                        ?>
                            <li><?=$item; ?></li>
                        <?php } ?>
                    </ul>
                </section>
                <section>
                    <h4>Logiciels</h4>
                    <ul>
                        <?php 
                        
                            foreach ($log as $item)
                            {
                        ?>
                            <li><?=$item; ?></li>
                        <?php } ?>
                    </ul>
                </section>
                <section>
                    <h4>Langues</h4>
                    <ul>
                        <?php 
                        
                            foreach ($lang as $item)
                            {
                        ?>
                            <li><?=$item; ?></li>
                        <?php } ?>
                    </ul>
                </section>
            </section>
        </main>
    </body>
</html>